version: "3.8"
services:

  # --- MinIO ---
  minio:
    image: minio/minio
    container_name: minio
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: admin
      MINIO_ROOT_PASSWORD: admin123
    volumes:
      - minio_data:/data
    command: server /data --console-address ":9001"

  # --- Jupyter ---
  jupyter:
    image: jupyter/scipy-notebook
    container_name: jupyter
    ports:
      - "8888:8888"
    volumes:
      - ./notebooks:/home/jovyan/work
    environment:
      JUPYTER_ENABLE_LAB: "yes"

  # --- Container Python livre ---
  python-runner:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: etl_runner
    volumes:
      - ./etl:/app/etl
      - ./data:/app/data
    command: ["tail", "-f", "/dev/null"]

  # --- Airflow Postgres ---
  postgres:
    image: postgres:13
    environment:
      POSTGRES_USER: airflow
      POSTGRES_PASSWORD: airflow
      POSTGRES_DB: airflow
    volumes:
      - postgres_data:/var/lib/postgresql/data

  # --- Airflow Redis ---
  redis:
    image: redis:latest

  # --- Airflow Webserver ---
  airflow-webserver:
    image: apache/airflow:2.7.1-python3.10
    build:
      context: ./airflow
    depends_on:
      - postgres
      - redis
    environment:
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__CORE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@postgres/airflow
      AIRFLOW__CORE__FERNET_KEY: ''
      AIRFLOW__CORE__LOAD_EXAMPLES: 'false'
    volumes:
      - ./dags:/opt/airflow/dags
    ports:
      - "8080:8080"
    command: webserver

  # --- Airflow Scheduler ---
  airflow-scheduler:
    image: apache/airflow:2.7.1-python3.10
    build:
      context: ./airflow
    depends_on:
      - airflow-webserver
    environment:
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__CORE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@postgres/airflow
    volumes:
      - ./dags:/opt/airflow/dags
    command: scheduler

volumes:
  minio_data:
  postgres_data:
